// This file is generated by scripts/generate-guide-registry.ts.
// Edit docs/*.md, then run npm run guides:generate.

import GrapheneOSPlatformManifestMd1 from '../../../docs/GrapheneOS_platform_manifest.md?raw';
import LineageOSAndroidMd2 from '../../../docs/LineageOS_android.md?raw';
import appleOssDistributionsXnuMd3 from '../../../docs/apple-oss-distributions_xnu.md?raw';
import bminorGlibcMd4 from '../../../docs/bminor_glibc.md?raw';
import freebsdFreebsdSrcMd5 from '../../../docs/freebsd_freebsd-src.md?raw';
import ghostbsdGhostbsdSrcMd6 from '../../../docs/ghostbsd_ghostbsd-src.md?raw';
import golangGoMd7 from '../../../docs/golang_go.md?raw';
import littlekernelLkMd8 from '../../../docs/littlekernel_lk.md?raw';
import llvmProjectMd9 from '../../../docs/llvm_project.md?raw';
import microsoftTypescriptGoMd10 from '../../../docs/microsoft_typescript-go.md?raw';
import mrcxlinuxSrv03rtmAnikaMd11 from '../../../docs/mrcxlinux_srv03rtm-anika.md?raw';
import nextbsdReduxNextbsdKernelMd12 from '../../../docs/nextbsd-redux_nextbsd-kernel.md?raw';
import ofdryadsMiniageosMd13 from '../../../docs/ofdryads_miniageos.md?raw';
import pythonCpythonMd14 from '../../../docs/python_cpython.md?raw';
import reactosReactosMd15 from '../../../docs/reactos_reactos.md?raw';
import seL4SeL4Md16 from '../../../docs/seL4_seL4.md?raw';
import torvaldsLinuxMd17 from '../../../docs/torvalds_linux.md?raw';

export const DOCS_MARKDOWN: Record<string, string> = {
  'GrapheneOS_platform_manifest.md': GrapheneOSPlatformManifestMd1,
  'LineageOS_android.md': LineageOSAndroidMd2,
  'apple-oss-distributions_xnu.md': appleOssDistributionsXnuMd3,
  'bminor_glibc.md': bminorGlibcMd4,
  'freebsd_freebsd-src.md': freebsdFreebsdSrcMd5,
  'ghostbsd_ghostbsd-src.md': ghostbsdGhostbsdSrcMd6,
  'golang_go.md': golangGoMd7,
  'littlekernel_lk.md': littlekernelLkMd8,
  'llvm_project.md': llvmProjectMd9,
  'microsoft_typescript-go.md': microsoftTypescriptGoMd10,
  'mrcxlinux_srv03rtm-anika.md': mrcxlinuxSrv03rtmAnikaMd11,
  'nextbsd-redux_nextbsd-kernel.md': nextbsdReduxNextbsdKernelMd12,
  'ofdryads_miniageos.md': ofdryadsMiniageosMd13,
  'python_cpython.md': pythonCpythonMd14,
  'reactos_reactos.md': reactosReactosMd15,
  'seL4_seL4.md': seL4SeL4Md16,
  'torvalds_linux.md': torvaldsLinuxMd17,
};
